### PR TITLE
Create a To-Do-List using React and Local Storage

### PR DESCRIPTION
**Pull request by Terbeche**
### ( This PR is only for Part 08 where I'm adding SVG icons using React )
- [Part 1 - React tutorial: The beginner's guide to learning React in 2020](https://ibaslogic.com/react-tutorial-for-beginners/).
- [Part 2 - Working with React form and handling event](https://ibaslogic.com/react-form-handling/).
- [Part 3 – How to implement CSS in Reactjs app](https://ibaslogic.com/css-in-reactjs-app/).
- [Part 4 – How to edit to-dos items](https://ibaslogic.com/how-to-edit-todos-items-in-react/).
- [Part 6 – Getting started with React lifecycle methods](https://ibaslogic.com/react-lifecycle-methods/).
- [Part 7 – Getting started with React hooks](https://ibaslogic.com/react-hooks-tutorial/).
- [Part 8 – How to use SVG icons in React](https://ibaslogic.com/how-to-use-svg-icons-in-react-project/).

### CODE REVIEW

**Review by wale-prog — CHANGES_REQUESTED** [review]
# Good job so far!

## Good Points 👍  
- Descriptive Pull request ✔️ 
- No linter errors ✔️ 
- Professional documentation ✔️ 

However, there are some issues that you still need to work on, but you are almost there.

# Changes Required ♻️ 
changes required

Please add the routes for the pages so that your App will be a complete single-page app, also add linter checks so that your code follows best practices.

**Comment by Terbeche** [comment]
Hi @wale-prog, I've made the necessary changes and deployed the app on Github pages. You can check it now.

**Review by wale-prog — APPROVED** [review]
Hi @Terbeche  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
- No linter error ✅ 
- Descriptive pull request ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by Terbeche** [comment]
@wale-prog, Thank you for the positive feedback!

**Review by wale-prog — COMMENTED** [review]
You are welcome 😀

**Pull request merged**
